# Generated by Django 5.1 on 2024-11-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Categoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstadoMaterial',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=100, null=True)),
            ],
            options={
                'db_table': 'EstadoMaterial',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PermisoNivel',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nivel', models.IntegerField(db_column='Nivel')),
                ('Descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=100, null=True)),
            ],
            options={
                'db_table': 'PermisoNivel',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo', models.CharField(db_column='Codigo', max_length=100)),
                ('Descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=500, null=True)),
                ('UnidadMedida', models.IntegerField(blank=True, db_column='UnidadMedida', null=True)),
                ('EstadoMaterial', models.IntegerField(blank=True, db_column='EstadoMaterial', null=True)),
                ('Minimo', models.IntegerField(blank=True, db_column='Minimo', null=True)),
                ('Maximo', models.IntegerField(blank=True, db_column='Maximo', null=True)),
                ('Categoria', models.IntegerField(blank=True, db_column='Categoria', null=True)),
                ('PuntoReorden', models.IntegerField(blank=True, db_column='PuntoReorden', null=True)),
                ('Proveedor', models.IntegerField(blank=True, db_column='Proveedor', null=True)),
                ('TiempoEntrega', models.IntegerField(blank=True, db_column='TiempoEntrega', null=True)),
                ('PedidoEstandar', models.IntegerField(blank=True, db_column='PedidoEstandar', null=True)),
                ('LoteMinimo', models.IntegerField(blank=True, db_column='LoteMinimo', null=True)),
                ('LoteMaximo', models.IntegerField(blank=True, db_column='LoteMaximo', null=True)),
                ('TiempoProcesoInterno', models.IntegerField(blank=True, db_column='TiempoProcesoInterno', null=True)),
                ('TiempoVidaUtil', models.IntegerField(blank=True, db_column='TiempoVidaUtil', null=True)),
                ('FichaTecnica', models.BinaryField(blank=True, db_column='FichaTecnica', null=True)),
            ],
            options={
                'db_table': 'Producto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Proveedor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=100, null=True)),
            ],
            options={
                'db_table': 'UnidadMedida',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('Activo', models.BooleanField(db_column='Activo', default=True)),
                ('PermisoNivel', models.IntegerField(db_column='PermisoNivel')),
            ],
            options={
                'db_table': 'Usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsuarioCodigo',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo', models.CharField(db_column='Codigo', max_length=100)),
            ],
            options={
                'db_table': 'UsuarioCodigo',
                'managed': True,
            },
        ),
    ]
