# Generated by Django 5.1 on 2024-11-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Contrasena',
            field=models.CharField(db_column='Contrasena', default='', max_length=50),
        ),
    ]
