# Generated by Django 5.1 on 2024-11-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usuario_contrasena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Contrasena',
            field=models.CharField(db_column='Contrasena', default='', max_length=500),
        ),
    ]
