# Generated by Django 5.1 on 2024-11-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_usuario_contrasena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Contrasena',
            field=models.BinaryField(db_column='Contrasena'),
        ),
    ]
