# Generated by Django 5.1 on 2024-12-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_clase_familia_segmento_producto_clase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='Segmento',
        ),
        migrations.RemoveField(
            model_name='segmento',
            name='Familia',
        ),
        migrations.AddField(
            model_name='clase',
            name='Familia',
            field=models.IntegerField(blank=True, db_column='Familia', null=True),
        ),
        migrations.AddField(
            model_name='familia',
            name='Segmento',
            field=models.IntegerField(blank=True, db_column='Segmento', null=True),
        ),
    ]
